export const bathroomsData = [
  {
    id: 1,
    name: "ห้องน้ำ เซ็นทรัลพลาซา เชียงใหม่ แอร์พอร์ต",
    location: "เซ็นทรัลพลาซา เชียงใหม่ แอร์พอร์ต",
    cleanliness: "สะอาด",
    image: "https://bathline.in.th/wp-content/uploads/2018/09/1.jpg",
    reviews: [],
    rating: 4.8,
    latitude: 13.7563,
    longitude: 100.5018,
},
{
    id: 2,
    name: "ห้องน้ำ เมย่า ไลฟ์สไตล์ ช้อปปิ้งเซ็นเตอร์",
    location: "ไมยา ไลฟ์สไตล์ ช้อปปิ้งเซ็นเตอร์",
    cleanliness: "สะอาด",
    image: "https://th.bing.com/th/id/R.a5ebf44450d35256ac0cb4a74898a55d?rik=RbexnKg42tFJVg&riu=http%3a%2f%2fwww.americanheritagecampground.com%2fwomens.jpg&ehk=uu3NKTQx23IdEpWk8FMEDGHEawcG%2btRB1v6b%2fzkQcrc%3d&risl=&pid=ImgRaw&r=0",
    reviews: [],
    rating: 4.5,
    latitude: 18.8046,
    longitude: 98.9665,
},
{
    id: 3,
    name: "ห้องน้ำ กาดสวนแก้ว",
    location: "กาดสวนแก้ว",
    cleanliness: "ปานกลาง",
    image: "https://th.bing.com/th/id/OIP._5R8SwKIHA-LE47qRJ7OrAAAAA?rs=1&pid=ImgDetMain",
    reviews: [],
    rating: 4.0,
    latitude: 18.8024,
    longitude: 98.9672,
},
{
    id: 4,
    name: "ห้องน้ำ โพรเมนาดา รีสอร์ท มอลล์",
    location: "โพรเมนาดา รีสอร์ท มอลล์",
    cleanliness: "สะอาด",
    image: "https://bathline.in.th/wp-content/uploads/2018/09/4.jpg",
    reviews: [],
    rating: 4.6,
    latitude: 18.7699,
    longitude: 99.0365,
},
{
    id: 5,
    name: "ห้องน้ำ เซ็นทรัลเฟสติวัล เชียงใหม่",
    location: "เซ็นทรัลเฟสติวัล เชียงใหม่",
    cleanliness: "สะอาด",
    image: "https://files.qatarliving.com/2019/07/10/LC-9.jpg",
    reviews: [],
    rating: 4.9,
    latitude: 18.7965,
    longitude: 99.0186,
},
{
    id: 6,
    name: "ห้องน้ำ วันนิมมาน",
    location: "วันนิมมาน",
    cleanliness: "สะอาด",
    image: "https://bathline.in.th/wp-content/uploads/2018/09/8.jpg",
    reviews: [],
    rating: 4.3,
    latitude: 18.8006,
    longitude: 98.9685,
},
{
    id: 7,
    name: "ห้องน้ำ ตลาด วโรรส",
    location: "ตลาดวโรรส",
    cleanliness: "ปานกลาง",
    image: "https://th.bing.com/th/id/R.3991fd15d16da100fa30d4e0c13fdc0e?rik=5HnY1s9V3tAOYQ&riu=http%3a%2f%2fnkds.kaist.ac.kr%2fresources%2fimages%2fdorm%2fhm%2froom5.jpg&ehk=G3PP%2b0xa3seGaqgvM68k0Ip%2bv%2b%2fvyRC9I3cqncZqi%2bw%3d&risl=&pid=ImgRaw&r=0",
    reviews: [],
    rating: 3.8,
    latitude: 18.7885,
    longitude: 98.9948,
},
{
    id: 8,
    name: "ห้องน้ำ เชียงใหม่ไนท์บาซาร์",
    location: "ไนท์บาซาร์เชียงใหม่",
    cleanliness: "สะอาด",
    image: "https://bathline.in.th/wp-content/uploads/2018/09/13.jpg",
    reviews: [],
    rating: 4.5,
    latitude: 18.7866,
    longitude: 98.9985,
},
{
  id: 9,
  name: "ห้องน้ำ PTT Station มหาวิทยาลัยเชียงใหม่",
  location: "PTT Station สาขา มหาวิทยาลัยเชียงใหม่",
  cleanliness: "สะอาด",
  image: "https://media-cdn.tripadvisor.com/media/photo-s/10/e8/18/c2/traditional-campground.jpg",
  reviews: [],
  rating: 4.2,
  latitude: 18.8015,
  longitude: 98.9554,
},
{
  id: 10,
  name: "ห้องน้ำ PTT Station กองบิน 41",
  location: "PTT Station กองบิน 41",
  cleanliness: "สะอาด",
  image: "https://th.bing.com/th/id/OIP.CKtUCN4SmT2FBgv53Cy3JQHaFj?rs=1&pid=ImgDetMain",
  reviews: [],
  rating: 4.1,
  latitude: 18.7724,
  longitude: 98.9695,
},
{
  id: 11,
  name: "ห้องน้ำ สวนบวกหาด",
  location: "สวนบวกหาด (Buak Hard Public Park)",
  cleanliness: "สะอาด",
  image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/71/c1/11/potato-creek-state-park.jpg?w=200&h=200&s=1",
  reviews: [],
  rating: 4.3,
  latitude: 18.7811,
  longitude: 98.9817,
},
{
  id: 12,
  name: "ห้องน้ำ สวน 700 ปี เชียงใหม่",
  location: "สวน 700 ปี เชียงใหม่ (Chiang Mai 700 Years Park)",
  cleanliness: "สะอาด",
  image: "https://s3-media0.fl.yelpcdn.com/bphoto/-KsuZU3ao-J0K7Enj6hiPA/348s.jpg",
  reviews: [],
  rating: 4.5,
  latitude: 18.8553,
  longitude: 98.9437,
},
{
  id: 13,
  name: "ห้องน้ำ Akha Ama Coffee",
  location: "Akha Ama Coffee",
  cleanliness: "สะอาด",
  image: "https://3.bp.blogspot.com/-8JMEnr0uucQ/WcfWGpU1pZI/AAAAAAAAAAM/SQ796zfJnNQpNX_N1fbGvKStD7Y357xhQCEwYBhgL/s1600/20170924_094713_1506268379071_resized.jpg",
  reviews: [],
  rating: 4.7,
  latitude: 18.7958,
  longitude: 98.9816,
},
{
  id: 14,
  name: "ห้องน้ำ The Hideout",
  location: "The Hideout",
  cleanliness: "สะอาด",
  image: "https://th.bing.com/th/id/OIP.n6QPy3nTAgT61kWi_iIUugHaEK?w=3167&h=1783&rs=1&pid=ImgDetMain",
  reviews: [],
  rating: 4.6,
  latitude: 18.7924,
  longitude: 98.9946,
},
{
  id: 13,
  name: "ห้องน้ำ สวนรมนา",
  location: "สวนรมนา (Rama IX Lanna Park)",
  cleanliness: "สะอาด",
  image: "https://th.bing.com/th/id/R.9285a9d93470b0a61125ca3f2608b765?rik=KJIlg6tY%2fC4u9g&riu=http%3a%2f%2fwww.bangkok.go.th%2fupload%2fnews%2f2017%2f07%2f01%2f201708101053200.jpg&ehk=8uJ6eCXPQ9DXY79DSf4Qw9H60Ub76VjbnyJ03Sc1Swo%3d&risl=&pid=ImgRaw&r=0",
  reviews: [],
  rating: 4.4,
  latitude: 18.8145,
  longitude: 98.9568,
},
{
  id: 14,
  name: "ห้องน้ำ สวนสัตว์เชียงใหม่",
  location: "สวนสัตว์เชียงใหม่ (Chiang Mai Zoo)",
  cleanliness: "สะอาด",
  image: "https://th.bing.com/th/id/OIP.tPHTsy-87C4rxFdsKFDK5gHaFj?pid=ImgDet&rs=1",
  reviews: [],
  rating: 4.2,
  latitude: 18.8315,
  longitude: 98.9738,
},
{
  id: 15,
  name: "ห้องน้ำ สวนสาธารณะหนองประทีป",
  location: "สวนสาธารณะหนองประทีป (Nong Prateep Park)",
  cleanliness: "สะอาด",
  image: "https://static.thairath.co.th/media/d7PbiDKEvWfYl3SInSNZg3NHC85b4Y5ZZ7U1gPQKgLR8.jpg",
  reviews: [],
  rating: 4.0,
  latitude: 18.7469,
  longitude: 98.9735,
},
{
  id: 16,
  name: "ห้องน้ำ สวนสาธารณะคลองแม่ข่า",
  location: "สวนสาธารณะคลองแม่ข่า (Mae Ka Canal Park)",
  cleanliness: "สะอาด",
  image: "https://www.tourismthailand.org/fileadmin/_processed_/8/7/csm_045-Large_8a0f80c64f.jpg",
  reviews: [],
  rating: 4.1,
  latitude: 18.7521,
  longitude: 98.9752,
},
{
  id: 17,
  name: "ห้องน้ำ สวนสาธารณะห้วยแก้ว",
  location: "สวนสาธารณะห้วยแก้ว (Huay Kaew Park)",
  cleanliness: "สะอาด",
  image: "https://th.bing.com/th/id/R.15ae2cb6e1896c5d78570aeaaaf3bc47?rik=E4R1Jkeoc%2bI5PQ&riu=http%3a%2f%2fwww.chiangmaifocus.com%2fwp-content%2fuploads%2f2022%2f05%2f%E0%B8%AA%E0%B8%A7%E0%B8%99%E0%B8%AB%E0%B9%88%E0%B8%A7%E0%B8%A2%E0%B9%81%E0%B8%81%E0%B9%89%E0%B8%A7.jpg&ehk=QwL%2b5BccS9u1kDRoM%2bG34%2b8DG%2bdCo3XUB7h4V5YCZg%3d&risl=&pid=ImgRaw&r=0",
  reviews: [],
  rating: 4.6,
  latitude: 18.7955,
  longitude: 98.9551,
},
{
  id: 18,
  name: "ห้องน้ำ สวนสาธารณะอ่างแก้ว",
  location: "สวนสาธารณะอ่างแก้ว (Ang Kaew Park)",
  cleanliness: "สะอาด",
  image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/AngKaew_Park_ChiangMai.jpg/800px-AngKaew_Park_ChiangMai.jpg",
  reviews: [],
  rating: 4.4,
  latitude: 18.8130,
  longitude: 98.9647,
},
{
  id: 19,
  name: "ห้องน้ำ Free Bird Cafe",
  location: "Free Bird Cafe",
  cleanliness: "สะอาด",
  image: "https://media-cdn.tripadvisor.com/media/photo-s/17/8e/44/d0/free-bird-cafe.jpg",
  reviews: [],
  rating: 4.5,
  latitude: 18.7865,
  longitude: 98.9740,
},
{
  id: 20,
  name: "ห้องน้ำ Ristr8to Lab",
  location: "Ristr8to Lab",
  cleanliness: "สะอาด",
  image: "https://media-cdn.tripadvisor.com/media/photo-s/15/3f/d4/94/ristr8to-lab.jpg",
  reviews: [],
  rating: 4.6,
  latitude: 18.7881,
  longitude: 98.9737,
},
{
  id: 21,
  name: "ห้องน้ำ Woo Cafe & Art Gallery",
  location: "Woo Cafe & Art Gallery",
  cleanliness: "สะอาด",
  image: "https://media-cdn.tripadvisor.com/media/photo-s/11/51/b5/0c/woo-cafe.jpg",
  reviews: [],
  rating: 4.7,
  latitude: 18.7854,
  longitude: 98.9774,
},
{
  id: 22,
  name: "ห้องน้ำ GRAPH Cafe",
  location: "GRAPH Cafe",
  cleanliness: "สะอาด",
  image: "https://media-cdn.tripadvisor.com/media/photo-s/09/56/61/68/graph-cafe.jpg",
  reviews: [],
  rating: 4.4,
  latitude: 18.7920,
  longitude: 98.9776,
},
{
  id: 23,
  name: "ห้องน้ำ Doppio at Central Festival Chiangmai",
  location: "Doppio at Central Festival Chiangmai",
  cleanliness: "สะอาด",
  image: "https://media-cdn.tripadvisor.com/media/photo-s/15/1b/3e/1f/doppio.jpg",
  reviews: [],
  rating: 4.5,
  latitude: 18.7739,
  longitude: 98.9646,
},
{
  id: 24,
  name: "ห้องน้ำ la.moon cold cafe",
  location: "la.moon cold cafe",
  cleanliness: "สะอาด",
  image: "https://media-cdn.tripadvisor.com/media/photo-s/11/0f/06/c8/la-moon-cold-cafe.jpg",
  reviews: [],
  rating: 4.4,
  latitude: 18.7970,
  longitude: 98.9632,
},
{
  id: 25,
  name: "ห้องน้ำ The Baristro At Train Station",
  location: "The Baristro At Train Station",
  cleanliness: "สะอาด",
  image: "https://media-cdn.tripadvisor.com/media/photo-s/17/8e/7d/34/baristro-at-train-station.jpg",
  reviews: [],
  rating: 4.5,
  latitude: 18.7751,
  longitude: 98.9798,
},
{
  id: 26,
  name: "ห้องน้ำ fringe.th",
  location: "fringe.th",
  cleanliness: "สะอาด",
  image: "https://media-cdn.tripadvisor.com/media/photo-s/11/1c/23/b7/fringe-th.jpg",
  reviews: [],
  rating: 4.3,
  latitude: 18.7833,
  longitude: 98.9747,
},
{
  id: 1,
  name: "ห้องน้ำ PTT Station สาขา ห้วยแก้ว",
  location: "PTT Station สาขา ห้วยแก้ว",
  cleanliness: "สะอาด",
  image: "https://example.com/ptt_huaykaew.jpg",
  reviews: [],
  rating: 4.3,
  latitude: 18.7974,
  longitude: 98.9647,
},
{
  id: 2,
  name: "ห้องน้ำ PTT Station สาขา ถนนมหิดล",
  location: "PTT Station สาขา ถนนมหิดล",
  cleanliness: "สะอาด",
  image: "https://example.com/ptt_mahidol.jpg",
  reviews: [],
  rating: 4.5,
  latitude: 18.7838,
  longitude: 98.9486,
},
{
  id: 3,
  name: "ห้องน้ำ PTT Station สาขา แม่โจ้",
  location: "PTT Station สาขา แม่โจ้",
  cleanliness: "สะอาด",
  image: "https://example.com/ptt_maejo.jpg",
  reviews: [],
  rating: 4.4,
  latitude: 18.8036,
  longitude: 98.9298,
},
{
  id: 4,
  name: "ห้องน้ำ PTT Station สาขา โครงการหลวง",
  location: "PTT Station สาขา โครงการหลวง",
  cleanliness: "สะอาด",
  image: "https://example.com/ptt_royal_project.jpg",
  reviews: [],
  rating: 4.6,
  latitude: 18.7920,
  longitude: 98.9752,
},
{
  id: 5,
  name: "ห้องน้ำ PTT Station สาขา นิมมาน",
  location: "PTT Station สาขา นิมมาน",
  cleanliness: "สะอาด",
  image: "https://example.com/ptt_nimman.jpg",
  reviews: [],
  rating: 4.5,
  latitude: 18.7880,
  longitude: 98.9784,
},
{
  id: 6,
  name: "ห้องน้ำ PTT Station แม่ริมขาออก (สุขุมเซอร์วิส)",
  location: "PTT Station แม่ริมขาออก (สุขุมเซอร์วิส)",
  cleanliness: "สะอาด",
  image: "https://example.com/ptt_maerim_out.jpg",
  reviews: [],
  rating: 4.4,
  latitude: 18.9541,
  longitude: 98.9621,
},
{
  id: 7,
  name: "ห้องน้ำ PTT Station จิฟฟี่ หนองจ๊อม",
  location: "PTT Station จิฟฟี่ หนองจ๊อม",
  cleanliness: "สะอาด",
  image: "https://example.com/ptt_jiffy_nongjom.jpg",
  reviews: [],
  rating: 4.3,
  latitude: 18.7450,
  longitude: 98.9943,
},
{
  id: 8,
  name: "ห้องน้ำ PTT Station หนองหาร",
  location: "PTT Station หนองหาร",
  cleanliness: "สะอาด",
  image: "https://example.com/ptt_nonghan.jpg",
  reviews: [],
  rating: 4.5,
  latitude: 18.7289,
  longitude: 98.9737,
},
{
  id: 9,
  name: "ห้องน้ำ PTT Station แม่ริม 1",
  location: "PTT Station แม่ริม 1",
  cleanliness: "สะอาด",
  image: "https://example.com/ptt_maerim_1.jpg",
  reviews: [],
  rating: 4.4,
  latitude: 18.9650,
  longitude: 98.9556,
},
{
  id: 10,
  name: "ห้องน้ำ PTT Station ป่าเหมือด",
  location: "PTT Station ป่าเหมือด",
  cleanliness: "สะอาด",
  image: "https://example.com/ptt_pamaed.jpg",
  reviews: [],
  rating: 4.3,
  latitude: 18.9034,
  longitude: 98.9494,
},
{
  id: 11,
  name: "ห้องน้ำ PTT Station สันทรายหลวง",
  location: "PTT Station สันทรายหลวง",
  cleanliness: "สะอาด",
  image: "https://example.com/ptt_sansailuang.jpg",
  reviews: [],
  rating: 4.5,
  latitude: 18.7417,
  longitude: 98.9881,
},
{
  id: 12,
  name: "ห้องน้ำ PTT Station สันนาเม็ง",
  location: "PTT Station สันนาเม็ง",
  cleanliness: "สะอาด",
  image: "https://example.com/ptt_sannameang.jpg",
  reviews: [],
  rating: 4.4,
  latitude: 18.7385,
  longitude: 98.9928,
},
{
  id: 13,
  name: "ห้องน้ำ PTT Station บ่อหิน",
  location: "PTT Station บ่อหิน",
  cleanliness: "สะอาด",
  image: "https://example.com/ptt_bohin.jpg",
  reviews: [],
  rating: 4.3,
  latitude: 18.7301,
  longitude: 98.9940,
},
{
  id: 14,
  name: "ห้องน้ำ PTT Station อีวี หนองจ๊อม",
  location: "PTT Station อีวี หนองจ๊อม",
  cleanliness: "สะอาด",
  image: "https://example.com/ptt_ev_nongjom.jpg",
  reviews: [],
  rating: 4.4,
  latitude: 18.7460,
  longitude: 98.9950,
},




  // เพิ่มห้องน้ำตามรายการคาเฟ่อื่น ๆ...
];